# Generated by Django 5.0.3 on 2026-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_announcement_exam'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academics.class'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academics.subject'),
        ),
    ]
